[project]
name = "nusagizi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clip",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "pip>=26.2.1",
    "requests>=2.34.2",
    "torch>=2.14.0",
    "ultralytics>=8.4.155",
]

[tool.uv.sources]
clip = { git = "https://github.com/ultralytics/CLIP.git" }
